spring:
  application:
    name: paystack-client
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.glassfish.jersey: ERROR
    org.reflections: ERROR
    com.github.viktority: DEBUG
  file:
    path: ${user.home}/corre/services/${spring.application.name}/logs
    name: ${logging.file.path}/${spring.application.name}.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] %X{CORRELATION_ID} %X{TENANT}:%X{USER} [%t] %c:%M - %msg%n'

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
feign:
  hystrix:
    enabled: true
paystack:
  server:
    url: https://api.paystack.co
  api:
    key:
      secret:
      public: